version: "3"
services:
  postgres_cadastro:
    container_name: postegres_cadastro_ifood
    image: postgres:13.0
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "54321:5432"