version: "3"
services:
  postgres_cadastro:
    container_name: postegres_cadastro_ifood
    image: postgres:13.0
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "54321:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:11.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"