version: "3"
services:
  postgres_cadastro:
    container_name: postegres_cadastro_ifood
    image: postgres:13.0
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "54321:5432"
  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:13.0
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "54322:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:11.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.20
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus_ifood:
    container_name: prometheus_ifood
    image: prometheus-ifood
    network_mode: "host"

  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:7.2.1
    network_mode: "host"

  artemis_ifood:
    container_name: artemis_ifood
    image: vromero/activemq-artemis:2.15.0
    network_mode: "host"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin

  mongodb_ifood:
    container_name: mongodb_ifood
    image: mongo:4.2.5-bionic
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pedido
      MONGO_INITDB_ROOT_PASSWORD: pedido
      MONGO_INITDB_DATABASE: pedido
